mybatis:
  configuration:
    # 全映射【嵌套对象，自动映射】
    auto-mapping-behavior: full
    # 驼峰命名
    map-underscore-to-camel-case: true
  # mapper.xml所在目录
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/hospital?currentSchema=authority
    username: postgres