# mybatis配置
mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
# 数据库配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/hospital?currentSchema=employee
    username: postgres
    password: 123456
